-----CREATE TABLE------


CREATE TABLE DFA_CINEMATICKET_DATA
(
Film_Type	VARCHAR(100),
film_code	VARCHAR(100),
cinema_code	VARCHAR(100),
total_sales	VARCHAR(100),
tickets_sold VARCHAR(100),	
tickets_out	VARCHAR(100),
show_time	VARCHAR(100),
occu_perc	VARCHAR(100),
ticket_price VARCHAR(100),	
ticket_use VARCHAR(100),	
capacity	VARCHAR(100),
t_date	VARCHAR(100),
t_month	VARCHAR(100),
t_quarter VARCHAR(100),	
t_day VARCHAR(100),
);

-----DISPLAY TABLE DATA------

SELECT * FROM DFA_CINEMATICKET_DATA;


-------CREATE TABLE-----


CREATE TABLE DFA_COVIDHEALTHCARE_DATA
(
DRG_ID	VARCHAR(100),
DRG_Definition	VARCHAR(100),
Provider_Id	VARCHAR(100),
Provider_Name	VARCHAR(100),
Provider_Street_Address	VARCHAR(100),
Provider_City	VARCHAR(100),
Provider_State	VARCHAR(100),
Provider_ZipCode VARCHAR(100),
Hospital_Referral_Region_Description VARCHAR(100),
Total_Discharges VARCHAR(100),	
Average_Covered_Charges	VARCHAR(100),
Average_Total_Payments	VARCHAR(100),
Average_Medicare_Payments VARCHAR(100)	
);

-----DISPLAY DATA IN TABLE-----
SELECT * FROM DFA_COVIDHEALTHCARE_DATA;


-----CREATE TABLE-----
CREATE TABLE DFA_COVIDHEALTHCARE_DATA1
(
DRG_ID	VARCHAR(100),
DRG_Definition	VARCHAR(100),
Provider_Id	VARCHAR(100),
Provider_Name	VARCHAR(100),
Provider_Street_Address	VARCHAR(100),
Provider_City	VARCHAR(100),
Provider_State	VARCHAR(100),
Provider_ZipCode VARCHAR(100),
Hospital_Referral_Region_Description VARCHAR(100),
Total_Discharges VARCHAR(100),	
Average_Covered_Charges	VARCHAR(100),
Average_Total_Payments	VARCHAR(100),
Average_Medicare_Payments VARCHAR(100)	
);


-----DISPLAY DATA IN TABLE-----
SELECT * FROM DFA_COVIDHEALTHCARE_DATA1;


SELECT * FROM DFA_INSURANCECLAIM_DATA;


-----CREATE TABLE -----

CREATE TABLE DFA_INSURANCE_CLAIM_HEALTHCARE_DATA
(
 PID varchar(50),
 AGE varchar(50),
 GENDER varchar(255),
 CASTE_NAME varchar(255),
 CATEGORY_CODE varchar(255),
 CATEGORY_NAME varchar(255),
 SURGERY_CODE varchar(255),
 SURGERY varchar(255),
 VILLAGE varchar(255),
 MANDAL_NAME varchar(255),
 DISTRICT_NAME varchar(255),
 PREAUTH_DATE varchar(50),
 PREAUTH_AMT varchar(50),
 CLAIM_DATE varchar(50),
 CLAIM_AMOUNT varchar(50),
 HOSP_NAME varchar(255),
 HOSP_TYPE varchar(50),
 HOSP_DISTRICT varchar(255),
 SURGERY_DATE varchar(50),
 DISCHARGE_DATE varchar(50),
 MORTALITY  varchar(255),
 MORTALITY_DATE varchar(50),
 SRC_REGISTRATION varchar(255)
);

-----VIEW TABLE DATA-----
SELECT * FROM DFA_INSURANCE_CLAIM_HEALTHCARE_DATA;


-----SOURCE TABLE FOR Scd type1-----
CREATE TABLE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(
 PID varchar(50),
 AGE varchar(50),
 GENDER varchar(255),
 CASTE_NAME varchar(255),
 CATEGORY_CODE varchar(255),
 CATEGORY_NAME varchar(255),
 SURGERY_CODE varchar(255),
 SURGERY varchar(255),
 VILLAGE varchar(255),
 MANDAL_NAME varchar(255),
 DISTRICT_NAME varchar(255),
 PREAUTH_DATE varchar(50),
 PREAUTH_AMT varchar(50),
 CLAIM_DATE varchar(50),
 CLAIM_AMOUNT varchar(50),
 HOSP_NAME varchar(255),
 HOSP_TYPE varchar(50),
 HOSP_DISTRICT varchar(255),
 SURGERY_DATE varchar(50),
 DISCHARGE_DATE varchar(50),
 MORTALITY  varchar(255),
 MORTALITY_DATE varchar(50),
 SRC_REGISTRATION varchar(255)
 );


SELECT * from DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE;

----INSERT VALUES TO TABLE-----
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'1', N'56', N'Female', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Lolugu', N'Ponduru', N'Srikakulam', N'8/3/2013 8:38:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/6/2013', N'9/7/2013', N'NO', N'5/6/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'2', N'37', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Borivanka', N'Kaviti', N'Srikakulam', N'8/6/2013 7:26:00 AM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/8/2013', N'9/9/2013', N'NO', N'15/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'3', N'50', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Kapasakuddi', N'Kaviti', N'Srikakulam', N'8/9/2013 6:30:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11500', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/15/2013', N'10/18/2013', N'NO', N'5/8/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'4', N'45', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Telikipenta', N'Sarubujjili', N'Srikakulam', N'8/24/2013 7:37:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/24/2013', N'9/27/2013', N'NO', N'9/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'5', N'54', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Thandemvalasa', N'Srikakulam', N'Srikakulam', N'8/28/2013 5:03:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/31/2013', N'10/2/2013', N'NO', N'8/9/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'6', N'35', N'Male', N'OC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Phasigangupeta', N'Pathapatnam', N'Srikakulam', N'8/28/2013 5:30:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/31/2013', N'10/2/2013', N'NO',N'8/5/2014', N'P')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'7', N'52', N'Male', N'OC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Kranti Nagar', N'Nandyal', N'Kurnool', N'8/30/2013 7:53:00 AM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Govt General Hospital Kurnool', N'G', N'Kurnool', N'8/31/2013', N'10/2/2013', N'NO',N'5/7/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'8', N'73', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Bhoghapuram', N'Bhoghapuram', N'Vizianagaram', N'5/2/2014 3:11:00 PM', N'12500', N'10/11/2017 7:34:00 PM', N'5000', N'Queens Nri Hospitals', N'C', N'Vishakhapatnam', N'5/5/2014',N'7/5/2014', N'YES', N'5/23/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'9', N'56', N'Male', N'OC', N'S7', N'CARDIAC AND CARDIOTHORACIC SURGERY', N'S7.1.1.1', N'Coronary Balloon Angioplasty with stent(00.45)', N'Vallur', N'Kakumanu', N'Guntur', N'6/10/2014 5:02:00 PM', N'40000', N'2/17/2017 7:21:00 PM', N'40000', N'Karumuri Hospital', N'C', N'Guntur', N'6/14/2014', N'6/16/2014', N'NO',N'7/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'10', N'49', N'Male', N'OC', N'S7', N'CARDIAC AND CARDIOTHORACIC SURGERY', N'S7.2.1.1', N'Coronary Bypass Surgery', N'Ward-15', N'Guntur(C)', N'Guntur', N'6/11/2014 8:41:00 PM', N'115846', N'2/17/2017 7:21:00 PM', N'115846', N'Karumuri Hospital', N'C', N'Guntur', N'6/17/2014', N'6/25/2014', N'NO', N'5/8/2014', N'D')




-----TARGET TABLE FOR Scd type2-----
CREATE TABLE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_TGT
(
 PID varchar(50),
 AGE varchar(50),
 GENDER varchar(255),
 CASTE_NAME varchar(255),
 CATEGORY_CODE varchar(255),
 CATEGORY_NAME varchar(255),
 SURGERY_CODE varchar(255),
 SURGERY varchar(255),
 VILLAGE varchar(255),
 MANDAL_NAME varchar(255),
 DISTRICT_NAME varchar(255),
 PREAUTH_DATE varchar(50),
 PREAUTH_AMT varchar(50),
 CLAIM_DATE varchar(50),
 CLAIM_AMOUNT varchar(50),
 HOSP_NAME varchar(255),
 HOSP_TYPE varchar(50),
 HOSP_DISTRICT varchar(255),
 SURGERY_DATE varchar(50),
 DISCHARGE_DATE varchar(50),
 MORTALITY  varchar(255),
 MORTALITY_DATE varchar(50),
 SRC_REGISTRATION varchar(255)
 );

SELECT * from DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_TGT;
SELECT * FROM DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE;

-----UPDATE Source table for Scd type1-----
update DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
set AGE=57
where pid=10;

update DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype1_SOURCE
set CASTE_NAME='BC'
where pid=10;

-----SOURCE TABLE FOR Scd type2-----

CREATE TABLE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(
 PID varchar(50),
 AGE varchar(50),
 GENDER varchar(255),
 CASTE_NAME varchar(255),
 CATEGORY_CODE varchar(255),
 CATEGORY_NAME varchar(255),
 SURGERY_CODE varchar(255),
 SURGERY varchar(255),
 VILLAGE varchar(255),
 MANDAL_NAME varchar(255),
 DISTRICT_NAME varchar(255),
 PREAUTH_DATE varchar(50),
 PREAUTH_AMT varchar(50),
 CLAIM_DATE varchar(50),
 CLAIM_AMOUNT varchar(50),
 HOSP_NAME varchar(255),
 HOSP_TYPE varchar(50),
 HOSP_DISTRICT varchar(255),
 SURGERY_DATE varchar(50),
 DISCHARGE_DATE varchar(50),
 MORTALITY  varchar(255),
 MORTALITY_DATE varchar(50),
 SRC_REGISTRATION varchar(255),
 );


-----INSERT VALUES TO TABLE-----
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'1', N'56', N'Female', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Lolugu', N'Ponduru', N'Srikakulam', N'8/3/2013 8:38:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/6/2013', N'9/7/2013', N'NO', N'5/6/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'2', N'37', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Borivanka', N'Kaviti', N'Srikakulam', N'8/6/2013 7:26:00 AM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/8/2013', N'9/9/2013', N'NO', N'15/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'3', N'50', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Kapasakuddi', N'Kaviti', N'Srikakulam', N'8/9/2013 6:30:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11500', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/15/2013', N'10/18/2013', N'NO', N'5/8/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'4', N'45', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Telikipenta', N'Sarubujjili', N'Srikakulam', N'8/24/2013 7:37:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/24/2013', N'9/27/2013', N'NO', N'9/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'5', N'54', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Thandemvalasa', N'Srikakulam', N'Srikakulam', N'8/28/2013 5:03:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/31/2013', N'10/2/2013', N'NO', N'8/9/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'6', N'35', N'Male', N'OC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Phasigangupeta', N'Pathapatnam', N'Srikakulam', N'8/28/2013 5:30:00 PM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Rims Govt. General Hospital, Srikakulam', N'G', N'Srikakulam', N'8/31/2013', N'10/2/2013', N'NO',N'8/5/2014', N'P')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'7', N'52', N'Male', N'OC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Kranti Nagar', N'Nandyal', N'Kurnool', N'8/30/2013 7:53:00 AM', N'12500', N'3/22/2017 8:25:00 PM', N'11000', N'Govt General Hospital Kurnool', N'G', N'Kurnool', N'8/31/2013', N'10/2/2013', N'NO',N'5/7/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'8', N'73', N'Male', N'BC', N'M6', N'NEPHROLOGY', N'M6.5', N'Maintenance Hemodialysis For Crf', N'Bhoghapuram', N'Bhoghapuram', N'Vizianagaram', N'5/2/2014 3:11:00 PM', N'12500', N'10/11/2017 7:34:00 PM', N'5000', N'Queens Nri Hospitals', N'C', N'Vishakhapatnam', N'5/5/2014',N'7/5/2014', N'YES', N'5/23/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'9', N'56', N'Male', N'OC', N'S7', N'CARDIAC AND CARDIOTHORACIC SURGERY', N'S7.1.1.1', N'Coronary Balloon Angioplasty with stent(00.45)', N'Vallur', N'Kakumanu', N'Guntur', N'6/10/2014 5:02:00 PM', N'40000', N'2/17/2017 7:21:00 PM', N'40000', N'Karumuri Hospital', N'C', N'Guntur', N'6/14/2014', N'6/16/2014', N'NO',N'7/5/2014', N'D')
INSERT INTO DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
(PID, AGE, GENDER, CASTE_NAME, CATEGORY_CODE, CATEGORY_NAME, SURGERY_CODE, SURGERY, VILLAGE, MANDAL_NAME, DISTRICT_NAME, PREAUTH_DATE, PREAUTH_AMT, CLAIM_DATE, CLAIM_AMOUNT, HOSP_NAME, HOSP_TYPE, HOSP_DISTRICT, SURGERY_DATE, DISCHARGE_DATE, Mortality, MORTALITY_DATE, SRC_REGISTRATION)
VALUES(N'10', N'49', N'Male', N'OC', N'S7', N'CARDIAC AND CARDIOTHORACIC SURGERY', N'S7.2.1.1', N'Coronary Bypass Surgery', N'Ward-15', N'Guntur(C)', N'Guntur', N'6/11/2014 8:41:00 PM', N'115846', N'2/17/2017 7:21:00 PM', N'115846', N'Karumuri Hospital', N'C', N'Guntur', N'6/17/2014', N'6/25/2014', N'NO', N'5/8/2014', N'D')


SELECT * FROM DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE;
SELECT * FROM DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_TGT;


-----TARGET TABLE for Scd type2-----
CREATE TABLE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_TGT
(
 PID varchar(50),
 AGE varchar(50),
 GENDER varchar(255),
 CASTE_NAME varchar(255),
 CATEGORY_CODE varchar(255),
 CATEGORY_NAME varchar(255),
 SURGERY_CODE varchar(255),
 SURGERY varchar(255),
 VILLAGE varchar(255),
 MANDAL_NAME varchar(255),
 DISTRICT_NAME varchar(255),
 PREAUTH_DATE varchar(50),
 PREAUTH_AMT varchar(50),
 CLAIM_DATE varchar(50),
 CLAIM_AMOUNT varchar(50),
 HOSP_NAME varchar(255),
 HOSP_TYPE varchar(50),
 HOSP_DISTRICT varchar(255),
 SURGERY_DATE varchar(50),
 DISCHARGE_DATE varchar(50),
 MORTALITY  varchar(255),
 MORTALITY_DATE varchar(50),
 SRC_REGISTRATION varchar(255),
 SDATE DATE,
 EDATE DATE,
 STATUS VARCHAR(50)
 );

-----UPDATE Source table for Scd type2-----
UPDATE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
SET DISTRICT_NAME='Guntur'
WHERE PID=10;


UPDATE DFA_INSURANCE_CLAIM_HEALTHCARE_SCDtype2_SOURCE
SET AGE=72
WHERE PID=10;

-----To view the values in table-----


SELECT * FROM DFA_FILMTICKET_SALES_AGGREGATE;
SELECT * FROM DFA_FILMTICKET_Aggregate;

SELECT * FROM DFA_CovidHC_Data_UnionAll;
SELECT * FROM DFA_CovidHCare_Data_UnionAll;

SELECT * FROM DFA_CovidHealthCare_DataAggegate;


SELECT * FROM DFA_CovidData_Aggregate;

SELECT * FROM DFA_CVD_Aggr;














